name: My First Workflow

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "The robot is awake"
     
      - name: Check out step
        uses: actions/checkout@v3
    
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: install pytest
        run: pip install pytest

      - name: run pytest
        run: pytest
    
      - name: print python version
        run: python --version

      - name: Look around the machine
        run: pwd && ls -la