name: my second workflow
on: workflow_dispatch
jobs:
  seocnd-job:
    runs-on: ubuntu-latest
    steps:
      - name: gretting and goodbye
        run: |
          echo "Hello"
          echo "goodbuye
  
